=== vanzin/jEdit/org/gjt/sp/jedit/syntax/xmode.dtd
<!-- Syntax tokens -->
<!ENTITY % tokens "( NULL | COMMENT1 | COMMENT2 | COMMENT3 | COMMENT4 |
	DIGIT | FUNCTION | INVALID | KEYWORD1 | KEYWORD2 | KEYWORD3 | KEYWORD4 |
	LABEL | LITERAL1 | LITERAL2 | LITERAL3 | LITERAL4 | MARKUP | OPERATOR )" >

<!-- Entities for attributes shared by multiple rules -->
<!ENTITY % att-bool '( TRUE | FALSE )' >
<!ENTITY % att-type 'TYPE %tokens; "NULL"' >
<!ENTITY % att-position-mix 'AT_LINE_START %att-bool; "FALSE"
	AT_WHITESPACE_END %att-bool; "FALSE"
	AT_WORD_START %att-bool; "FALSE"' >
<!ENTITY % att-exclude-match 'EXCLUDE_MATCH %att-bool; "FALSE"' >
<!ENTITY % att-delegate 'DELEGATE CDATA #IMPLIED' >
<!ENTITY % att-span-mix 'NO_LINE_BREAK %att-bool; "FALSE"
	NO_WORD_BREAK %att-bool; "FALSE"
	NO_ESCAPE %att-bool; "FALSE"'>
<!ENTITY % att-hash-char 'HASH_CHAR CDATA #REQUIRED' >

<!-- MODE element -->
<!ELEMENT MODE ( PROPS?, RULES* ) >

<!-- MODE children -->
<!-- PROPS element -->
<!ELEMENT PROPS ( PROPERTY+ ) >

<!-- PROPS children -->
<!ELEMENT PROPERTY EMPTY >
<!ATTLIST PROPERTY
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED >

<!-- RULES element -->
<!ELEMENT RULES ( PROPS?, ( TERMINATE | SEQ | SEQ_REGEXP | SPAN | SPAN_REGEXP
	| EOL_SPAN | EOL_SPAN_REGEXP | MARK_PREVIOUS
	| MARK_FOLLOWING )*, KEYWORDS? ) >

<!-- RULES attributes -->
<!ATTLIST RULES
	SET CDATA "MAIN"
	IGNORE_CASE %att-bool; "TRUE"
	HIGHLIGHT_DIGITS %att-bool; "FALSE"
	DIGIT_RE CDATA #IMPLIED
	ESCAPE CDATA #IMPLIED
	DEFAULT %tokens; "NULL"
	NO_WORD_SEP CDATA "_">

<!-- TERMINATE element -->
<!ELEMENT TERMINATE EMPTY >
<!ATTLIST TERMINATE AT_CHAR CDATA #REQUIRED >

<!-- SEQ element -->
<!ELEMENT SEQ ( #PCDATA ) >

<!-- SEQ attributes -->
<!ATTLIST SEQ
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SEQ_REGEXP element -->
<!ELEMENT SEQ_REGEXP ( #PCDATA ) >

<!-- SEQ_REGEXP attributes -->
<!ATTLIST SEQ_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SPAN element -->
<!ELEMENT SPAN ( BEGIN, END ) >

<!-- SPAN attributes -->
<!ATTLIST SPAN
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN_REGEXP element -->
<!ELEMENT SPAN_REGEXP ( BEGIN, END ) >

<!-- SPAN_REGEXP attributes -->
<!ATTLIST SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN and SPAN_REGEXP children -->
<!ELEMENT BEGIN ( #PCDATA ) >
<!ATTLIST BEGIN %att-position-mix; >
<!ELEMENT END ( #PCDATA ) >
<!ATTLIST END %att-position-mix; >

<!-- EOL_SPAN element -->
<!ELEMENT EOL_SPAN ( #PCDATA ) >

<!-- EOL_SPAN attributes -->
<!ATTLIST EOL_SPAN
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- EOL_SPAN_REGEXP element -->
<!ELEMENT EOL_SPAN_REGEXP ( #PCDATA ) >

<!-- EOL_SPAN_REGEXP attributes -->
<!ATTLIST EOL_SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- MARK_FOLLOWING element -->
<!ELEMENT MARK_FOLLOWING ( #PCDATA ) >

<!-- MARK_FOLLOWING attributes -->
<!ATTLIST MARK_FOLLOWING
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- MARK_PREVIOUS element -->
<!ELEMENT MARK_PREVIOUS ( #PCDATA ) >

<!-- MARK_PREVIOUS attributes -->
<!ATTLIST MARK_PREVIOUS
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- KEYWORDS element -->
<!ELEMENT KEYWORDS (%tokens;)+ >

<!-- KEYWORDS children -->
<!ELEMENT COMMENT1 ( #PCDATA ) >
<!ELEMENT COMMENT2 ( #PCDATA ) >
<!ELEMENT COMMENT3 ( #PCDATA ) >
<!ELEMENT COMMENT4 ( #PCDATA ) >
<!ELEMENT DIGIT ( #PCDATA ) >
<!ELEMENT FUNCTION ( #PCDATA ) >
<!ELEMENT KEYWORD1 ( #PCDATA ) >
<!ELEMENT KEYWORD2 ( #PCDATA ) >
<!ELEMENT KEYWORD3 ( #PCDATA ) >
<!ELEMENT KEYWORD4 ( #PCDATA ) >
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT LITERAL1 ( #PCDATA ) >
<!ELEMENT LITERAL2 ( #PCDATA ) >
<!ELEMENT LITERAL3 ( #PCDATA ) >
<!ELEMENT LITERAL4 ( #PCDATA ) >
<!ELEMENT MARKUP ( #PCDATA ) >
<!ELEMENT NULL ( #PCDATA ) >
<!ELEMENT OPERATOR ( #PCDATA ) >
<!ELEMENT INVALID ( #PCDATA ) >

=== vanzin/jEdit/modes/netrexx.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<!-- the ; hack is there so that stuff like if(bob) fred();
		  -- does not indent the next line -->
		<PROPERTY NAME="indentPrevLine" VALUE="\s*(((if|while)\s*\(|else|case|default)[^;]*|for\s*\(.*)" />
		<!-- set this to 'true' if you want to use GNU coding style -->
		<PROPERTY NAME="doubleBracketIndent" VALUE="false" />
		<PROPERTY NAME="commentStart" VALUE="/*" />
		<PROPERTY NAME="commentEnd" VALUE="*/" />
		<PROPERTY NAME="lineComment" VALUE="--" />
		<PROPERTY NAME="noWordSep" VALUE="_" />
		<PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="TRUE" HIGHLIGHT_DIGITS="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>    </WHITESPACE>

		<!-- Documentation comment -->
		<SPAN TYPE="COMMENT2" DELEGATE="java::JAVADOC">
			<BEGIN>/**</BEGIN>
			<END>*/</END>
		</SPAN>

		<!-- C style comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>/*</BEGIN>
			<END>*/</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<EOL_SPAN TYPE="COMMENT1">--</EOL_SPAN>

		<SEQ TYPE="NULL">(</SEQ>
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>

		<!-- workaround to stop "*" from being colorized
		  -- in import statements. -->
		<SEQ TYPE="NULL">.*</SEQ>

		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">?</SEQ>
		<MARK_PREVIOUS TYPE="LABEL" EXCLUDE_MATCH="TRUE"
			AT_LINE_START="TRUE">:</MARK_PREVIOUS>
		<SEQ TYPE="NULL">:</SEQ>

		<KEYWORDS IGNORE_CASE="TRUE">
			<KEYWORD1>abbrev</KEYWORD1>
			<KEYWORD1>abs</KEYWORD1>
			<KEYWORD1>b2x</KEYWORD1>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>catch</KEYWORD1>
			<KEYWORD1>center</KEYWORD1>
			<KEYWORD1>changestr</KEYWORD1>
			<KEYWORD1>compare</KEYWORD1>
			<KEYWORD1>copies</KEYWORD1>
			<KEYWORD1>countstr</KEYWORD1>
			<KEYWORD1>c2d</KEYWORD1>
			<KEYWORD1>c2x</KEYWORD1>
			<KEYWORD1>datatype</KEYWORD1>
			<KEYWORD1>delstr</KEYWORD1>
			<KEYWORD1>delword</KEYWORD1>
			<KEYWORD1>d2c</KEYWORD1>
			<KEYWORD1>d2X</KEYWORD1>
			<KEYWORD1>exists</KEYWORD1>
			<KEYWORD1>format</KEYWORD1>
			<KEYWORD1>insert</KEYWORD1>
			<KEYWORD1>lastpos</KEYWORD1>
			<KEYWORD1>left</KEYWORD1>
			<KEYWORD1>length</KEYWORD1>
			<KEYWORD1>lower</KEYWORD1>
			<KEYWORD1>max</KEYWORD1>
			<KEYWORD1>min</KEYWORD1>
			<KEYWORD1>overlay</KEYWORD1>
			<KEYWORD1>pos</KEYWORD1>
			<KEYWORD1>reverse</KEYWORD1>
			<KEYWORD1>right</KEYWORD1>
			<KEYWORD1>say</KEYWORD1>
			<KEYWORD1>sequence</KEYWORD1>
			<KEYWORD1>sign</KEYWORD1>
			<KEYWORD1>space</KEYWORD1>
			<KEYWORD1>strip</KEYWORD1>
			<KEYWORD1>substr</KEYWORD1>
			<KEYWORD1>subword</KEYWORD1>
			<KEYWORD1>trunc</KEYWORD1>
			<KEYWORD1>upper</KEYWORD1>
			<KEYWORD1>verify</KEYWORD1>
			<KEYWORD1>word</KEYWORD1>
			<KEYWORD1>wordindex</KEYWORD1>
			<KEYWORD1>wordlength</KEYWORD1>
			<KEYWORD1>wordpos</KEYWORD1>
			<KEYWORD1>words</KEYWORD1>
			<KEYWORD1>x2b</KEYWORD1>
			<KEYWORD1>x2c</KEYWORD1>
			<KEYWORD1>x2d</KEYWORD1>

			<KEYWORD2>do</KEYWORD2>
			<KEYWORD2>while</KEYWORD2>
			<KEYWORD2>if</KEYWORD2>
			<KEYWORD2>then</KEYWORD2>
			<KEYWORD2>else</KEYWORD2>
			<KEYWORD2>end</KEYWORD2>
			<KEYWORD2>select</KEYWORD2>
			<KEYWORD2>loop</KEYWORD2>
			<KEYWORD2>over</KEYWORD2>
			<KEYWORD2>iterate</KEYWORD2>
			<KEYWORD2>leave</KEYWORD2>
			<KEYWORD2>exit</KEYWORD2>
			<KEYWORD2>trace</KEYWORD2>
			<KEYWORD2>numeric</KEYWORD2>
			<KEYWORD2>options</KEYWORD2>
			<KEYWORD2>package</KEYWORD2>
			<KEYWORD2>import</KEYWORD2>
			<KEYWORD2>options</KEYWORD2>

			<KEYWORD3>method</KEYWORD3>
			<KEYWORD3>class</KEYWORD3>
			<KEYWORD3>properties</KEYWORD3>


		</KEYWORDS>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/shellscript.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="#" />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="TRUE" HIGHLIGHT_DIGITS="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- Comments -->
		<EOL_SPAN TYPE="COMMENT2">#!</EOL_SPAN>
		<EOL_SPAN TYPE="COMMENT1">#</EOL_SPAN>

		<!-- Variables -->
		<SPAN TYPE="KEYWORD2" NO_LINE_BREAK="TRUE">
			<BEGIN>${</BEGIN>
			<END>}</END>
		</SPAN>

		<MARK_FOLLOWING TYPE="KEYWORD2">$#</MARK_FOLLOWING>
		<MARK_FOLLOWING TYPE="KEYWORD2">$?</MARK_FOLLOWING>
		<MARK_FOLLOWING TYPE="KEYWORD2">$*</MARK_FOLLOWING>
		<MARK_FOLLOWING TYPE="KEYWORD2">$&lt;</MARK_FOLLOWING>
		<MARK_FOLLOWING TYPE="KEYWORD2">$</MARK_FOLLOWING>

		<!-- weird stuff -->
		<SPAN TYPE="KEYWORD3" DELEGATE="EXEC">
			<BEGIN>$((</BEGIN>
			<END>))</END>
		</SPAN>
		<SPAN TYPE="KEYWORD3" DELEGATE="EXEC">
			<BEGIN>$(</BEGIN>
			<END>)</END>
		</SPAN>
		<SPAN TYPE="KEYWORD3" DELEGATE="EXEC">
			<BEGIN>$[</BEGIN>
			<END>]</END>
		</SPAN>
		<SPAN TYPE="KEYWORD3" DELEGATE="EXEC">
			<BEGIN>`</BEGIN>
			<END>`</END>
		</SPAN>

		<!-- Literals -->
		<SPAN TYPE="LITERAL1" DELEGATE="LITERAL">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<!-- Readins -->
		<SPAN TYPE="LITERAL1" DELEGATE="LITERAL">
			<BEGIN>&lt;&lt;EOF</BEGIN>
			<END>EOF</END>
		</SPAN>

		<!-- Operators -->
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>

		<!-- %jobnumber -->
		<MARK_FOLLOWING TYPE="KEYWORD2">%</MARK_FOLLOWING>

		<!-- some of these should be marked OPERATOR -->
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="NULL">(</SEQ>
		<SEQ TYPE="NULL">=</SEQ>
		<SEQ TYPE="NULL">!</SEQ>
		<SEQ TYPE="NULL">&gt;=</SEQ>
		<SEQ TYPE="NULL">&lt;=</SEQ>
		<SEQ TYPE="NULL">+</SEQ>
		<SEQ TYPE="NULL">-</SEQ>
		<SEQ TYPE="NULL">/</SEQ>
		<SEQ TYPE="NULL">*</SEQ>
		<SEQ TYPE="NULL">^</SEQ>
		<SEQ TYPE="NULL">~</SEQ>
		<SEQ TYPE="NULL">}</SEQ>
		<SEQ TYPE="NULL">{</SEQ>
		<!-- SEQ TYPE="NULL">.</SEQ -->
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">?</SEQ>
		<SEQ TYPE="NULL">:</SEQ>
	</RULES>

	<RULES SET="LITERAL" DEFAULT="LITERAL1" ESCAPE="\">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- Variables -->
		<SPAN TYPE="KEYWORD2" NO_LINE_BREAK="TRUE">
			<BEGIN>${</BEGIN>
			<END>}</END>
		</SPAN>

		<MARK_FOLLOWING TYPE="KEYWORD2">$</MARK_FOLLOWING>
	</RULES>

	<RULES SET="EXEC" DEFAULT="KEYWORD3" ESCAPE="\">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- Variables -->
		<SPAN TYPE="KEYWORD2" NO_LINE_BREAK="TRUE">
			<BEGIN>${</BEGIN>
			<END>}</END>
		</SPAN>

		<SPAN TYPE="KEYWORD3">
			<BEGIN>$((</BEGIN>
			<END>))</END>
		</SPAN>

		<SPAN TYPE="KEYWORD3">
			<BEGIN>$(</BEGIN>
			<END>)</END>
		</SPAN>

		<SPAN TYPE="KEYWORD3">
			<BEGIN>$[</BEGIN>
			<END>]</END>
		</SPAN>

		<MARK_FOLLOWING TYPE="KEYWORD2">$</MARK_FOLLOWING>

		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/batch.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="rem " />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="TRUE">
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- 'echo off' statements -->
		<SEQ TYPE="KEYWORD3">@</SEQ>

		<!-- labels -- eg :test -->
		<EOL_SPAN TYPE="LABEL" AT_LINE_START="TRUE">:</EOL_SPAN>

		<!-- comments -->
		<EOL_SPAN TYPE="COMMENT1">REM</EOL_SPAN>

		<!-- literals -->
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<!-- variables -->
		<SEQ TYPE="KEYWORD2">%1</SEQ>
		<SEQ TYPE="KEYWORD2">%2</SEQ>
		<SEQ TYPE="KEYWORD2">%3</SEQ>
		<SEQ TYPE="KEYWORD2">%4</SEQ>
		<SEQ TYPE="KEYWORD2">%5</SEQ>
		<SEQ TYPE="KEYWORD2">%6</SEQ>
		<SEQ TYPE="KEYWORD2">%7</SEQ>
		<SEQ TYPE="KEYWORD2">%8</SEQ>
		<SEQ TYPE="KEYWORD2">%9</SEQ>
		<SPAN TYPE="KEYWORD2" NO_LINE_BREAK="TRUE">
			<BEGIN>%</BEGIN>
			<END>%</END>
		</SPAN>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/python.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- Python mode, by Slava Pestov. Based on PythonTokenMarker by -->
<!-- Jonathan Revusky -->

<!-- Modified 19-Jul-00 by Ivan Frohne to: -->
<!--  (a) implement 'indentOnEnter'; -->
<!--  (b) indent next line automatically after control structures followed -->
<!--	  by ':'; -->
<!--  (c) make """ or ''' multiline quotes TYPE LITERAL2; -->
<!--  (d) add TYPE FUNCTION identified by a following '(' -->
<!--  (e) eliminate the '?' SEQ TYPE ('?' has no meaning in Python); -->
<!--  (f) change the TYPE of 'and', 'or', and 'not' to KEYWORD1; and -->
<!--  (g) add all builtin functions, builtin exceptions, -->
<!--	  builtin type methods, File object methods, and special type -->
<!--	  attributes as TYPE KEYWORD3. -->

<MODE>
	<PROPS>
		<PROPERTY NAME="indentPrevLine" VALUE="\s*.{3,}:\s*(#.*)?" />
		<PROPERTY NAME="lineComment" VALUE="#" />
		<PROPERTY NAME="noWordSep" VALUE="_" />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- Comment -->
		<EOL_SPAN TYPE="COMMENT1">#</EOL_SPAN>

		<!-- Triple-quotes -->
		<SPAN TYPE="LITERAL2">
			<BEGIN>"""</BEGIN>
			<END>"""</END>
		</SPAN>

		<SPAN TYPE="LITERAL2">
			<BEGIN>'''</BEGIN>
			<END>'''</END>
		</SPAN>

		<!-- Standard literals -->
		<SPAN TYPE="LITERAL1">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="NULL">}</SEQ>
		<SEQ TYPE="NULL">{</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">:</SEQ>

		<MARK_PREVIOUS TYPE="FUNCTION"
			EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

		<KEYWORDS IGNORE_CASE="FALSE">
			<!--  Reserved Words  -->
			<KEYWORD1>and</KEYWORD1>
			<KEYWORD1>as</KEYWORD1>
			<KEYWORD1>assert</KEYWORD1>
			<KEYWORD1>break</KEYWORD1>
			<KEYWORD1>class</KEYWORD1>
			<KEYWORD1>continue</KEYWORD1>
			<KEYWORD1>def</KEYWORD1>
			<KEYWORD1>del</KEYWORD1>
			<KEYWORD1>elif</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>except</KEYWORD1>
			<KEYWORD1>exec</KEYWORD1>
			<KEYWORD1>finally</KEYWORD1>
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>from</KEYWORD1>
			<KEYWORD1>global</KEYWORD1>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>import</KEYWORD1>
			<KEYWORD1>in</KEYWORD1>
			<KEYWORD1>is</KEYWORD1>
			<KEYWORD1>lambda</KEYWORD1>
			<KEYWORD1>not</KEYWORD1>
			<KEYWORD1>or</KEYWORD1>
			<KEYWORD1>pass</KEYWORD1>
			<KEYWORD1>print</KEYWORD1>
			<KEYWORD1>raise</KEYWORD1>
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>try</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD1>yield</KEYWORD1>

			<!-- builtins -->
			<KEYWORD2>abs</KEYWORD2>
			<KEYWORD2>apply</KEYWORD2>
			<KEYWORD2>buffer</KEYWORD2>
			<KEYWORD2>callable</KEYWORD2>
			<KEYWORD2>chr</KEYWORD2>
			<KEYWORD2>cmp</KEYWORD2>
			<KEYWORD2>coerce</KEYWORD2>
			<KEYWORD2>compile</KEYWORD2>
			<KEYWORD2>complex</KEYWORD2>
			<KEYWORD2>delattr</KEYWORD2>
			<KEYWORD2>dir</KEYWORD2>
			<KEYWORD2>divmod</KEYWORD2>
			<KEYWORD2>eval</KEYWORD2>
			<KEYWORD2>execfile</KEYWORD2>
			<KEYWORD2>filter</KEYWORD2>
			<KEYWORD2>float</KEYWORD2>
			<KEYWORD2>getattr</KEYWORD2>
			<KEYWORD2>globals</KEYWORD2>
			<KEYWORD2>hasattr</KEYWORD2>
			<KEYWORD2>hash</KEYWORD2>
			<KEYWORD2>help</KEYWORD2>
			<KEYWORD2>hex</KEYWORD2>
			<KEYWORD2>id</KEYWORD2>
			<KEYWORD2>input</KEYWORD2>
			<KEYWORD2>int</KEYWORD2>
			<KEYWORD2>intern</KEYWORD2>
			<KEYWORD2>isinstance</KEYWORD2>
			<KEYWORD2>issubclass</KEYWORD2>
			<KEYWORD2>len</KEYWORD2>
			<KEYWORD2>list</KEYWORD2>
			<KEYWORD2>locals</KEYWORD2>
			<KEYWORD2>long</KEYWORD2>
			<KEYWORD2>map</KEYWORD2>
			<KEYWORD2>max</KEYWORD2>
			<KEYWORD2>min</KEYWORD2>
			<KEYWORD2>oct</KEYWORD2>
			<KEYWORD2>open</KEYWORD2>
			<KEYWORD2>ord</KEYWORD2>
			<KEYWORD2>pow</KEYWORD2>
			<KEYWORD2>range</KEYWORD2>
			<KEYWORD2>raw_input</KEYWORD2>
			<KEYWORD2>reduce</KEYWORD2>
			<KEYWORD2>reload</KEYWORD2>
			<KEYWORD2>repr</KEYWORD2>
			<KEYWORD2>round</KEYWORD2>
			<KEYWORD2>setattr</KEYWORD2>
			<KEYWORD2>slice</KEYWORD2>
			<KEYWORD2>str</KEYWORD2>
			<KEYWORD2>tuple</KEYWORD2>
			<KEYWORD2>type</KEYWORD2>
			<KEYWORD2>unichr</KEYWORD2>
			<KEYWORD2>unicode</KEYWORD2>
			<KEYWORD2>vars</KEYWORD2>
			<KEYWORD2>xrange</KEYWORD2>
			<KEYWORD2>zip</KEYWORD2>

			<!-- exceptions -->
			<KEYWORD3>ArithmeticError</KEYWORD3>
			<KEYWORD3>AssertionError</KEYWORD3>
			<KEYWORD3>AttributeError</KEYWORD3>
			<KEYWORD3>DeprecationWarning</KEYWORD3>
			<KEYWORD3>EOFError</KEYWORD3>
			<KEYWORD3>EnvironmentError</KEYWORD3>
			<KEYWORD3>Exception</KEYWORD3>
			<KEYWORD3>FloatingPointError</KEYWORD3>
			<KEYWORD3>IOError</KEYWORD3>
			<KEYWORD3>ImportError</KEYWORD3>
			<KEYWORD3>IndentationError</KEYWORD3>
			<KEYWORD3>IndexError</KEYWORD3>
			<KEYWORD3>KeyError</KEYWORD3>
			<KEYWORD3>KeyboardInterrupt</KEYWORD3>
			<KEYWORD3>LookupError</KEYWORD3>
			<KEYWORD3>MemoryError</KEYWORD3>
			<KEYWORD3>NameError</KEYWORD3>
			<KEYWORD3>NotImplemented</KEYWORD3>
			<KEYWORD3>NotImplementedError</KEYWORD3>
			<KEYWORD3>OSError</KEYWORD3>
			<KEYWORD3>OverflowError</KEYWORD3>
			<KEYWORD3>RuntimeError</KEYWORD3>
			<KEYWORD3>RuntimeWarning</KEYWORD3>
			<KEYWORD3>StandardError</KEYWORD3>
			<KEYWORD3>SyntaxError</KEYWORD3>
			<KEYWORD3>SyntaxWarning</KEYWORD3>
			<KEYWORD3>SystemError</KEYWORD3>
			<KEYWORD3>SystemExit</KEYWORD3>
			<KEYWORD3>TabError</KEYWORD3>
			<KEYWORD3>TypeError</KEYWORD3>
			<KEYWORD3>UnboundLocalError</KEYWORD3>
			<KEYWORD3>UnicodeError</KEYWORD3>
			<KEYWORD3>UserWarning</KEYWORD3>
			<KEYWORD3>ValueError</KEYWORD3>
			<KEYWORD3>Warning</KEYWORD3>
			<KEYWORD3>WindowsError</KEYWORD3>
			<KEYWORD3>ZeroDivisionError</KEYWORD3>

			<!-- types (from types module) -->
			<KEYWORD3>BufferType</KEYWORD3>
			<KEYWORD3>BuiltinFunctionType</KEYWORD3>
			<KEYWORD3>BuiltinMethodType</KEYWORD3>
			<KEYWORD3>ClassType</KEYWORD3>
			<KEYWORD3>CodeType</KEYWORD3>
			<KEYWORD3>ComplexType</KEYWORD3>
			<KEYWORD3>DictType</KEYWORD3>
			<KEYWORD3>DictionaryType</KEYWORD3>
			<KEYWORD3>EllipsisType</KEYWORD3>
			<KEYWORD3>FileType</KEYWORD3>
			<KEYWORD3>FloatType</KEYWORD3>
			<KEYWORD3>FrameType</KEYWORD3>
			<KEYWORD3>FunctionType</KEYWORD3>
			<KEYWORD3>InstanceType</KEYWORD3>
			<KEYWORD3>IntType</KEYWORD3>
			<KEYWORD3>LambdaType</KEYWORD3>
			<KEYWORD3>ListType</KEYWORD3>
			<KEYWORD3>LongType</KEYWORD3>
			<KEYWORD3>MethodType</KEYWORD3>
			<KEYWORD3>ModuleType</KEYWORD3>
			<KEYWORD3>NoneType</KEYWORD3>
			<KEYWORD3>SliceType</KEYWORD3>
			<KEYWORD3>StringType</KEYWORD3>
			<KEYWORD3>TracebackType</KEYWORD3>
			<KEYWORD3>TupleType</KEYWORD3>
			<KEYWORD3>TypeType</KEYWORD3>
			<KEYWORD3>UnboundMethodType</KEYWORD3>
			<KEYWORD3>UnicodeType</KEYWORD3>
			<KEYWORD3>XRangeType</KEYWORD3>

			<KEYWORD3>None</KEYWORD3>

			<KEYWORD3>__all__</KEYWORD3>
			<KEYWORD3>__bases__</KEYWORD3>
			<KEYWORD3>__builtins__</KEYWORD3>
			<KEYWORD3>__class__</KEYWORD3>
			<KEYWORD3>__debug__</KEYWORD3>
			<KEYWORD3>__dict__</KEYWORD3>
			<KEYWORD3>__doc__</KEYWORD3>
			<KEYWORD3>__file__</KEYWORD3>
			<KEYWORD3>__future__</KEYWORD3>
			<KEYWORD3>__import__</KEYWORD3>
			<KEYWORD3>__members__</KEYWORD3>
			<KEYWORD3>__methods__</KEYWORD3>
			<KEYWORD3>__name__</KEYWORD3>
			<KEYWORD3>__path__</KEYWORD3>
			<KEYWORD3>__self__</KEYWORD3>
			<KEYWORD3>__version__</KEYWORD3>
		</KEYWORDS>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/actionscript.xml
<?xml version="1.0"?>
<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!--
	ActionScript mode by Ben Glazer <ben@enspire.com>
	Adapted from JavaScript mode by Andre Kaplan
-->
<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="/*" />
		<PROPERTY NAME="commentEnd" VALUE="*/" />
		<PROPERTY NAME="lineComment" VALUE="//" />
		<PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />

		<!-- Auto indent -->
		<PROPERTY NAME="indentOpenBrackets" VALUE="{" />
		<PROPERTY NAME="indentCloseBrackets" VALUE="}" />
		<PROPERTY NAME="indentNextLine"
			VALUE="\s*(((if|while)\s*\(|else\s*|else\s+if\s*\(|for\s*\(.*\))[^{;]*)" />
		<!-- set this to 'true' if you want to use GNU coding style -->
		<PROPERTY NAME="doubleBracketIndent" VALUE="false" />
		<PROPERTY NAME="lineUpClosingBracket" VALUE="true" />
	</PROPS>

	<RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
		<SPAN TYPE="COMMENT1">
			<BEGIN>/*</BEGIN>
			<END>*/</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

		<EOL_SPAN TYPE="COMMENT1">//</EOL_SPAN>

		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>
		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="OPERATOR">.</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="OPERATOR">,</SEQ>
		<SEQ TYPE="OPERATOR">;</SEQ>
		<SEQ TYPE="OPERATOR">]</SEQ>
		<SEQ TYPE="OPERATOR">[</SEQ>
		<SEQ TYPE="OPERATOR">?</SEQ>
		<MARK_PREVIOUS AT_WHITESPACE_END="TRUE"
			EXCLUDE_MATCH="TRUE"
			TYPE="LABEL">:</MARK_PREVIOUS>
		<SEQ TYPE="OPERATOR">:</SEQ>

		<KEYWORDS>
			<!-- ActionScript's reserved words (see AS:TDG p.332) -->
			<KEYWORD1>add</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>and</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>break</KEYWORD1>
			<KEYWORD1>continue</KEYWORD1>
			<KEYWORD1>delete</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>eq</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>function</KEYWORD1>
			<KEYWORD1>ge</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>gt</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>ifFrameLoaded</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>in</KEYWORD1>
			<KEYWORD1>le</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>lt</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>ne</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>new</KEYWORD1>
			<KEYWORD1>not</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>on</KEYWORD1>
			<KEYWORD1>onClipEvent</KEYWORD1>
			<KEYWORD1>or</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>return</KEYWORD1>
			<LITERAL2>this</LITERAL2>
			<KEYWORD1>tellTarget</KEYWORD1>   <!-- deprecated -->
			<KEYWORD1>typeof</KEYWORD1>
			<KEYWORD1>var</KEYWORD1>
			<KEYWORD3>void</KEYWORD3>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD1>with</KEYWORD1>

			<!-- Built-in objects (good idea not to use these names!)-->
			<KEYWORD3>Array</KEYWORD3>
			<KEYWORD3>Boolean</KEYWORD3>
			<KEYWORD3>Color</KEYWORD3>
			<KEYWORD3>Date</KEYWORD3>
			<KEYWORD3>Function</KEYWORD3>
			<KEYWORD3>Key</KEYWORD3>
			<KEYWORD3>MovieClip</KEYWORD3>
			<KEYWORD3>Math</KEYWORD3>
			<KEYWORD3>Mouse</KEYWORD3>
			<KEYWORD3>Number</KEYWORD3>
			<KEYWORD3>Object</KEYWORD3>
			<KEYWORD3>Selection</KEYWORD3>
			<KEYWORD3>Sound</KEYWORD3>
			<KEYWORD3>String</KEYWORD3>
			<KEYWORD3>XML</KEYWORD3>
			<KEYWORD3>XMLNode</KEYWORD3>
			<KEYWORD3>XMLSocket</KEYWORD3>

			<!-- Literals -->
			<LITERAL2>NaN</LITERAL2>
			<LITERAL2>Infinity</LITERAL2>
			<LITERAL2>false</LITERAL2>
			<LITERAL2>null</LITERAL2>
			<LITERAL2>true</LITERAL2>
			<LITERAL2>undefined</LITERAL2>

			<!-- Global functions -->
			<LITERAL2>Boolean</LITERAL2>
			<LITERAL2>call</LITERAL2>
			<LITERAL2>Date</LITERAL2>
			<LITERAL2>duplicateMovieClip</LITERAL2>
			<LITERAL2>escape</LITERAL2>
			<LITERAL2>eval</LITERAL2>
			<LITERAL2>fscommand</LITERAL2>
			<LITERAL2>getProperty</LITERAL2>
			<LITERAL2>getTimer</LITERAL2>
			<LITERAL2>getURL</LITERAL2>
			<LITERAL2>getVersion</LITERAL2>
			<LITERAL2>gotoAndPlay</LITERAL2>
			<LITERAL2>gotoAndStop</LITERAL2>
			<LITERAL2>#include</LITERAL2>
			<LITERAL2>int</LITERAL2>   <!-- deprecated -->
			<LITERAL2>isFinite</LITERAL2>
			<LITERAL2>isNaN</LITERAL2>
			<LITERAL2>loadMovie</LITERAL2>
			<LITERAL2>loadMovieNum</LITERAL2>
			<LITERAL2>loadVariables</LITERAL2>
			<LITERAL2>loadVariablesNum</LITERAL2>
			<LITERAL2>maxscroll</LITERAL2>
			<LITERAL2>newline</LITERAL2>
			<LITERAL2>nextFrame</LITERAL2>
			<LITERAL2>nextScene</LITERAL2>
			<LITERAL2>Number</LITERAL2>
			<LITERAL2>parseFloat</LITERAL2>
			<LITERAL2>parseInt</LITERAL2>
			<LITERAL2>play</LITERAL2>
			<LITERAL2>prevFrame</LITERAL2>
			<LITERAL2>prevScene</LITERAL2>
			<LITERAL2>print</LITERAL2>
			<LITERAL2>printAsBitmap</LITERAL2>
			<LITERAL2>printAsBitmapNum</LITERAL2>
			<LITERAL2>printNum</LITERAL2>
			<LITERAL2>random</LITERAL2>   <!-- deprecated -->
			<LITERAL2>removeMovieClip</LITERAL2>
			<LITERAL2>scroll</LITERAL2>
			<LITERAL2>setProperty</LITERAL2>
			<LITERAL2>startDrag</LITERAL2>
			<LITERAL2>stop</LITERAL2>
			<LITERAL2>stopAllSounds</LITERAL2>
			<LITERAL2>stopDrag</LITERAL2>
			<LITERAL2>String</LITERAL2>
			<LITERAL2>targetPath</LITERAL2>
			<LITERAL2>tellTarget</LITERAL2>   <!-- deprecated -->
			<LITERAL2>toggleHighQuality</LITERAL2>   <!-- deprecated -->
			<LITERAL2>trace</LITERAL2>
			<LITERAL2>unescape</LITERAL2>
			<LITERAL2>unloadMovie</LITERAL2>
			<LITERAL2>unloadMovieNum</LITERAL2>
			<LITERAL2>updateAfterEvent</LITERAL2>

			<!--ECMAScript keywords-->
			<!-- Reserved for future use 
				(some are already used in some Javascript Engines) 
			-->
			<KEYWORD1>abstract</KEYWORD1>
			<KEYWORD3>boolean</KEYWORD3>
			<KEYWORD3>byte</KEYWORD3>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>catch</KEYWORD1>
			<KEYWORD3>char</KEYWORD3>
			<KEYWORD1>class</KEYWORD1>
			<KEYWORD1>const</KEYWORD1>
			<KEYWORD1>debugger</KEYWORD1>
			<KEYWORD1>default</KEYWORD1>

			<KEYWORD3>double</KEYWORD3>
			<KEYWORD1>enum</KEYWORD1>
			<KEYWORD2>export</KEYWORD2>
			<KEYWORD1>extends</KEYWORD1>
			<KEYWORD1>final</KEYWORD1>
			<KEYWORD1>finally</KEYWORD1>
			<KEYWORD3>float</KEYWORD3>
			<KEYWORD1>goto</KEYWORD1>
			<KEYWORD1>implements</KEYWORD1>

			<KEYWORD2>import</KEYWORD2>
			<KEYWORD1>instanceof</KEYWORD1>
			<KEYWORD3>int</KEYWORD3>
			<KEYWORD1>interface</KEYWORD1>
			<KEYWORD3>long</KEYWORD3>
			<KEYWORD1>native</KEYWORD1>
			<KEYWORD2>package</KEYWORD2>
			<KEYWORD1>private</KEYWORD1>
			<KEYWORD1>protected</KEYWORD1>
			<KEYWORD1>public</KEYWORD1>

			<KEYWORD3>short</KEYWORD3>
			<KEYWORD1>static</KEYWORD1>
			<LITERAL2>super</LITERAL2>
			<KEYWORD1>switch</KEYWORD1>
			<KEYWORD1>synchronized</KEYWORD1>
			<KEYWORD1>throw</KEYWORD1>
			<KEYWORD1>throws</KEYWORD1>
			<KEYWORD1>transient</KEYWORD1>
			<KEYWORD1>try</KEYWORD1>
			<KEYWORD1>volatile</KEYWORD1>
		</KEYWORDS>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/texinfo.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="@c" />
	</PROPS>
	<RULES>
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- comments -->
		<EOL_SPAN TYPE="COMMENT1">@c </EOL_SPAN>
		<EOL_SPAN TYPE="COMMENT1">@comment </EOL_SPAN>

		<!-- @... commands -->
		<MARK_FOLLOWING TYPE="KEYWORD1">@</MARK_FOLLOWING>

		<!-- word separators -->
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="NULL">(</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">=</SEQ>
		<SEQ TYPE="NULL">!</SEQ>
		<SEQ TYPE="NULL">+</SEQ>
		<SEQ TYPE="NULL">-</SEQ>
		<SEQ TYPE="NULL">/</SEQ>
		<SEQ TYPE="NULL">*</SEQ>
		<SEQ TYPE="NULL">&gt;</SEQ>
		<SEQ TYPE="NULL">&lt;</SEQ>
		<SEQ TYPE="NULL">&amp;</SEQ>
		<SEQ TYPE="NULL">|</SEQ>
		<SEQ TYPE="NULL">^</SEQ>
		<SEQ TYPE="NULL">~</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">?</SEQ>
		<SEQ TYPE="NULL">:</SEQ>
		<SEQ TYPE="NULL">'</SEQ>
		<SEQ TYPE="NULL">"</SEQ>
		<SEQ TYPE="NULL">`</SEQ>
		<SEQ TYPE="NULL">\</SEQ>
	</RULES>
</MODE>
