=== vanzin/jEdit/org/gjt/sp/jedit/syntax/xmode.dtd
<!-- Syntax tokens -->
<!ENTITY % tokens "( NULL | COMMENT1 | COMMENT2 | COMMENT3 | COMMENT4 |
	DIGIT | FUNCTION | INVALID | KEYWORD1 | KEYWORD2 | KEYWORD3 | KEYWORD4 |
	LABEL | LITERAL1 | LITERAL2 | LITERAL3 | LITERAL4 | MARKUP | OPERATOR )" >

<!-- Entities for attributes shared by multiple rules -->
<!ENTITY % att-bool '( TRUE | FALSE )' >
<!ENTITY % att-type 'TYPE %tokens; "NULL"' >
<!ENTITY % att-position-mix 'AT_LINE_START %att-bool; "FALSE"
	AT_WHITESPACE_END %att-bool; "FALSE"
	AT_WORD_START %att-bool; "FALSE"' >
<!ENTITY % att-exclude-match 'EXCLUDE_MATCH %att-bool; "FALSE"' >
<!ENTITY % att-delegate 'DELEGATE CDATA #IMPLIED' >
<!ENTITY % att-span-mix 'NO_LINE_BREAK %att-bool; "FALSE"
	NO_WORD_BREAK %att-bool; "FALSE"
	NO_ESCAPE %att-bool; "FALSE"'>
<!ENTITY % att-hash-char 'HASH_CHAR CDATA #REQUIRED' >

<!-- MODE element -->
<!ELEMENT MODE ( PROPS?, RULES* ) >

<!-- MODE children -->
<!-- PROPS element -->
<!ELEMENT PROPS ( PROPERTY+ ) >

<!-- PROPS children -->
<!ELEMENT PROPERTY EMPTY >
<!ATTLIST PROPERTY
	NAME CDATA #REQUIRED
	VALUE CDATA #REQUIRED >

<!-- RULES element -->
<!ELEMENT RULES ( PROPS?, ( TERMINATE | SEQ | SEQ_REGEXP | SPAN | SPAN_REGEXP
	| EOL_SPAN | EOL_SPAN_REGEXP | MARK_PREVIOUS
	| MARK_FOLLOWING )*, KEYWORDS? ) >

<!-- RULES attributes -->
<!ATTLIST RULES
	SET CDATA "MAIN"
	IGNORE_CASE %att-bool; "TRUE"
	HIGHLIGHT_DIGITS %att-bool; "FALSE"
	DIGIT_RE CDATA #IMPLIED
	ESCAPE CDATA #IMPLIED
	DEFAULT %tokens; "NULL"
	NO_WORD_SEP CDATA "_">

<!-- TERMINATE element -->
<!ELEMENT TERMINATE EMPTY >
<!ATTLIST TERMINATE AT_CHAR CDATA #REQUIRED >

<!-- SEQ element -->
<!ELEMENT SEQ ( #PCDATA ) >

<!-- SEQ attributes -->
<!ATTLIST SEQ
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SEQ_REGEXP element -->
<!ELEMENT SEQ_REGEXP ( #PCDATA ) >

<!-- SEQ_REGEXP attributes -->
<!ATTLIST SEQ_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-delegate; >

<!-- SPAN element -->
<!ELEMENT SPAN ( BEGIN, END ) >

<!-- SPAN attributes -->
<!ATTLIST SPAN
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN_REGEXP element -->
<!ELEMENT SPAN_REGEXP ( BEGIN, END ) >

<!-- SPAN_REGEXP attributes -->
<!ATTLIST SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-span-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- SPAN and SPAN_REGEXP children -->
<!ELEMENT BEGIN ( #PCDATA ) >
<!ATTLIST BEGIN %att-position-mix; >
<!ELEMENT END ( #PCDATA ) >
<!ATTLIST END %att-position-mix; >

<!-- EOL_SPAN element -->
<!ELEMENT EOL_SPAN ( #PCDATA ) >

<!-- EOL_SPAN attributes -->
<!ATTLIST EOL_SPAN
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- EOL_SPAN_REGEXP element -->
<!ELEMENT EOL_SPAN_REGEXP ( #PCDATA ) >

<!-- EOL_SPAN_REGEXP attributes -->
<!ATTLIST EOL_SPAN_REGEXP
	%att-hash-char;
	%att-type;
	%att-position-mix;
	%att-exclude-match;
	%att-delegate; >

<!-- MARK_FOLLOWING element -->
<!ELEMENT MARK_FOLLOWING ( #PCDATA ) >

<!-- MARK_FOLLOWING attributes -->
<!ATTLIST MARK_FOLLOWING
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- MARK_PREVIOUS element -->
<!ELEMENT MARK_PREVIOUS ( #PCDATA ) >

<!-- MARK_PREVIOUS attributes -->
<!ATTLIST MARK_PREVIOUS
	%att-type;
	%att-position-mix;
	%att-exclude-match; >

<!-- KEYWORDS element -->
<!ELEMENT KEYWORDS (%tokens;)+ >

<!-- KEYWORDS children -->
<!ELEMENT COMMENT1 ( #PCDATA ) >
<!ELEMENT COMMENT2 ( #PCDATA ) >
<!ELEMENT COMMENT3 ( #PCDATA ) >
<!ELEMENT COMMENT4 ( #PCDATA ) >
<!ELEMENT DIGIT ( #PCDATA ) >
<!ELEMENT FUNCTION ( #PCDATA ) >
<!ELEMENT KEYWORD1 ( #PCDATA ) >
<!ELEMENT KEYWORD2 ( #PCDATA ) >
<!ELEMENT KEYWORD3 ( #PCDATA ) >
<!ELEMENT KEYWORD4 ( #PCDATA ) >
<!ELEMENT LABEL ( #PCDATA ) >
<!ELEMENT LITERAL1 ( #PCDATA ) >
<!ELEMENT LITERAL2 ( #PCDATA ) >
<!ELEMENT LITERAL3 ( #PCDATA ) >
<!ELEMENT LITERAL4 ( #PCDATA ) >
<!ELEMENT MARKUP ( #PCDATA ) >
<!ELEMENT NULL ( #PCDATA ) >
<!ELEMENT OPERATOR ( #PCDATA ) >
<!ELEMENT INVALID ( #PCDATA ) >

=== vanzin/jEdit/4-4-pre1/modes/html.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="&lt;!--" />
		<PROPERTY NAME="commentEnd" VALUE="--&gt;" />
	</PROPS>

	<RULES IGNORE_CASE="TRUE">
		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<!-- JavaScript -->
		<SPAN TYPE="MARKUP" DELEGATE="JAVASCRIPT">
			<BEGIN>&lt;SCRIPT</BEGIN>
			<END>&lt;/SCRIPT&gt;</END>
		</SPAN>

		<!-- stylesheet -->
		<SPAN TYPE="MARKUP" DELEGATE="CSS">
			<BEGIN>&lt;STYLE</BEGIN>
			<END>&lt;/STYLE&gt;</END>
		</SPAN>

		<!-- DTD instructions -->
		<SPAN TYPE="KEYWORD2" DELEGATE="xml::DTD-TAGS">
			<BEGIN>&lt;!</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- markup tags -->
		<SPAN TYPE="MARKUP" DELEGATE="TAGS">
			<BEGIN>&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- SGML entities -->
		<SPAN TYPE="LITERAL2" NO_WORD_BREAK="TRUE">
			<BEGIN>&amp;</BEGIN>
			<END>;</END>
		</SPAN>
	</RULES>

	<!-- ESCAPE is not exactly right but it is needed to correctly
	     handle JavaScript in on* parameters.
             NOTE: ESCAPE moved from RULE to SPANs! -->
	<RULES SET="TAGS" DEFAULT="MARKUP">
		<!-- Inline CSS -->
 		<SPAN_REGEXP AT_WORD_START="TRUE" TYPE="MARKUP" DELEGATE="css::PROPERTIES" HASH_CHAR="style">
			<BEGIN>style\s*=\s*(["'])</BEGIN>
			<END>$1</END>
		</SPAN_REGEXP>

		<!-- Javascript: delegate on* attributes to Javascript mode -->
 		<SPAN_REGEXP AT_WORD_START="TRUE" DELEGATE="javascript::MAIN" HASH_CHAR="on" TYPE="MARKUP">
			<BEGIN>on[a-z]+\s*=\s*(["'])</BEGIN>
			<END>$1</END>
		</SPAN_REGEXP>

		<!-- NOTE: no ESCAPE for quotes, at least for attributes; e.g onclick="alert(\"foo\");" is invalid! -->
		<SPAN TYPE="LITERAL1">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">=</SEQ>

		<KEYWORDS>
			<!-- HTML/XHTML elements, taken from http://de.selfhtml.org/html/referenz/elemente.htm -->
			<MARKUP>a</MARKUP>
			<MARKUP>abbr</MARKUP>
			<MARKUP>acronym</MARKUP>
			<MARKUP>address</MARKUP>
			<MARKUP>applet</MARKUP>
			<MARKUP>area</MARKUP>
			<MARKUP>b</MARKUP>
			<MARKUP>base</MARKUP>
			<MARKUP>basefont</MARKUP>
			<MARKUP>bdo</MARKUP>
			<MARKUP>big</MARKUP>
			<MARKUP>blockquote</MARKUP>
			<MARKUP>body</MARKUP>
			<MARKUP>br</MARKUP>
			<MARKUP>button</MARKUP>
			<MARKUP>caption</MARKUP>
			<MARKUP>center</MARKUP>
			<MARKUP>cite</MARKUP>
			<MARKUP>code</MARKUP>
			<MARKUP>col</MARKUP>
			<MARKUP>colgroup</MARKUP>
			<MARKUP>dd</MARKUP>
			<MARKUP>del</MARKUP>
			<MARKUP>dfn</MARKUP>
			<MARKUP>dir</MARKUP>
			<MARKUP>div</MARKUP>
			<MARKUP>dl</MARKUP>
			<MARKUP>dt</MARKUP>
			<MARKUP>em</MARKUP>
			<MARKUP>fieldset</MARKUP>
			<MARKUP>font</MARKUP>
			<MARKUP>form</MARKUP>
			<MARKUP>frame</MARKUP>
			<MARKUP>frameset</MARKUP>
			<MARKUP>h1</MARKUP>
			<MARKUP>h2</MARKUP>
			<MARKUP>h3</MARKUP>
			<MARKUP>h4</MARKUP>
			<MARKUP>h5</MARKUP>
			<MARKUP>h6</MARKUP>
			<MARKUP>head</MARKUP>
			<MARKUP>hr</MARKUP>
			<MARKUP>html</MARKUP>
			<MARKUP>i</MARKUP>
			<MARKUP>iframe</MARKUP>
			<MARKUP>img</MARKUP>
			<MARKUP>input</MARKUP>
			<MARKUP>ins</MARKUP>
			<MARKUP>isindex</MARKUP>
			<MARKUP>kbd</MARKUP>
			<MARKUP>label</MARKUP>
			<MARKUP>legend</MARKUP>
			<MARKUP>li</MARKUP>
			<MARKUP>link</MARKUP>
			<MARKUP>map</MARKUP>
			<MARKUP>menu</MARKUP>
			<MARKUP>meta</MARKUP>
			<MARKUP>noframes</MARKUP>
			<MARKUP>noscript</MARKUP>
			<MARKUP>object</MARKUP>
			<MARKUP>ol</MARKUP>
			<MARKUP>optgroup</MARKUP>
			<MARKUP>option</MARKUP>
			<MARKUP>p</MARKUP>
			<MARKUP>param</MARKUP>
			<MARKUP>pre</MARKUP>
			<MARKUP>q</MARKUP>
			<MARKUP>s</MARKUP>
			<MARKUP>samp</MARKUP>
			<MARKUP>script</MARKUP>
			<MARKUP>select</MARKUP>
			<MARKUP>small</MARKUP>
			<MARKUP>span</MARKUP>
			<MARKUP>strike</MARKUP>
			<MARKUP>strong</MARKUP>
			<MARKUP>style</MARKUP>
			<MARKUP>sub</MARKUP>
			<MARKUP>sup</MARKUP>
			<MARKUP>table</MARKUP>
			<MARKUP>tbody</MARKUP>
			<MARKUP>td</MARKUP>
			<MARKUP>textarea</MARKUP>
			<MARKUP>tfoot</MARKUP>
			<MARKUP>th</MARKUP>
			<MARKUP>thead</MARKUP>
			<MARKUP>title</MARKUP>
			<MARKUP>tr</MARKUP>
			<MARKUP>tt</MARKUP>
			<MARKUP>u</MARKUP>
			<MARKUP>ul</MARKUP>
			<MARKUP>var</MARKUP>
		</KEYWORDS>
	</RULES>

	<RULES SET="JAVASCRIPT" DEFAULT="MARKUP" IGNORE_CASE="TRUE">
		<SEQ TYPE="MARKUP" DELEGATE="javascript::MAIN">&gt;</SEQ>
		<!-- handle <SCRIPT SRC="..."> properly -->
		<SEQ TYPE="MARKUP" DELEGATE="BACK_TO_HTML">SRC=</SEQ>

		<!-- Inline CSS -->
 		<SPAN_REGEXP TYPE="MARKUP" DELEGATE="css::PROPERTIES" HASH_CHAR="style">
			<BEGIN>style\s*=\s*(["'])</BEGIN>
			<END>$1</END>
		</SPAN_REGEXP>
	</RULES>

	<RULES SET="BACK_TO_HTML" DEFAULT="MARKUP">
		<SEQ TYPE="MARKUP" DELEGATE="html::MAIN">&gt;</SEQ>
	</RULES>

	<RULES SET="CSS" DEFAULT="MARKUP">
		<SEQ TYPE="MARKUP" DELEGATE="css::MAIN">&gt;</SEQ>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/c.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="indentOpenBrackets" VALUE="{" />
		<PROPERTY NAME="indentCloseBrackets" VALUE="}" />
		<!-- the ; hack is there so that stuff like if(bob) fred();
		     does not indent the next line -->
		<PROPERTY NAME="indentPrevLine" VALUE="\s*(((if|while)\s*\(|else|case|default)[^;]*|for\s*\(.*)" />
		<!-- set this to 'true' if you want to use GNU coding style -->
		<PROPERTY NAME="doubleBracketIndent" VALUE="false" />
		<PROPERTY NAME="commentStart" VALUE="/*" />
		<PROPERTY NAME="commentEnd" VALUE="*/" />
		<PROPERTY NAME="lineComment" VALUE="//" />
		<PROPERTY NAME="noWordSep" VALUE="_" />
		<PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- C style comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>/*</BEGIN>
			<END>*/</END>
		</SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<!-- preprocessor statements -->
		<EOL_SPAN TYPE="KEYWORD2">#</EOL_SPAN>

		<EOL_SPAN TYPE="COMMENT1">//</EOL_SPAN>
		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>

		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">?</SEQ>
		<MARK_PREVIOUS TYPE="LABEL" EXCLUDE_MATCH="TRUE"
			AT_LINE_START="TRUE">:</MARK_PREVIOUS>
		<SEQ TYPE="NULL">:</SEQ>

		<!-- Function calls -->
		<MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

		<KEYWORDS IGNORE_CASE="FALSE">
			<KEYWORD3>char</KEYWORD3>
			<KEYWORD3>double</KEYWORD3>
			<KEYWORD3>enum</KEYWORD3>
			<KEYWORD3>float</KEYWORD3>
			<KEYWORD3>int</KEYWORD3>
			<KEYWORD3>long</KEYWORD3>
			<KEYWORD3>short</KEYWORD3>
			<KEYWORD3>signed</KEYWORD3>
			<KEYWORD3>struct</KEYWORD3>
			<KEYWORD3>typedef</KEYWORD3>
			<KEYWORD3>union</KEYWORD3>
			<KEYWORD3>unsigned</KEYWORD3>
			<KEYWORD3>void</KEYWORD3>
			<KEYWORD1>auto</KEYWORD1>
			<KEYWORD1>const</KEYWORD1>
			<KEYWORD1>extern</KEYWORD1>
			<KEYWORD1>register</KEYWORD1>
			<KEYWORD1>static</KEYWORD1>
			<KEYWORD1>volatile</KEYWORD1>
			<KEYWORD1>break</KEYWORD1>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>continue</KEYWORD1>
			<KEYWORD1>default</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>goto</KEYWORD1>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>sizeof</KEYWORD1>
			<KEYWORD1>switch</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD2>asm</KEYWORD2>
			<KEYWORD2>asmlinkage</KEYWORD2>
			<KEYWORD2>far</KEYWORD2>
			<KEYWORD2>huge</KEYWORD2>
			<KEYWORD2>inline</KEYWORD2>
			<KEYWORD2>near</KEYWORD2>
			<KEYWORD2>pascal</KEYWORD2>
			<LITERAL2>true</LITERAL2>
			<LITERAL2>false</LITERAL2>
			<LITERAL2>NULL</LITERAL2>
		</KEYWORDS>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/html.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="&lt;!--" />
		<PROPERTY NAME="commentEnd" VALUE="--&gt;" />
	</PROPS>
	<RULES IGNORE_CASE="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<!-- JavaScript -->
		<SPAN TYPE="MARKUP" DELEGATE="javascript::MAIN">
			<BEGIN>&lt;SCRIPT&gt;</BEGIN>
			<END>&lt;/SCRIPT&gt;</END>
		</SPAN>

		<!-- stylesheet -->
		<SPAN TYPE="MARKUP" DELEGATE="css::MAIN">
			<BEGIN>&lt;STYLE&gt;</BEGIN>
			<END>&lt;/STYLE&gt;</END>
		</SPAN>

		<!-- DTD instructions -->
		<SPAN TYPE="KEYWORD2" DELEGATE="xml::DTD-TAGS">
			<BEGIN>&lt;!</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- markup tags -->
		<SPAN TYPE="MARKUP" DELEGATE="TAGS">
			<BEGIN>&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- SGML entities -->
		<SPAN TYPE="LITERAL2" NO_WORD_BREAK="TRUE">
			<BEGIN>&amp;</BEGIN>
			<END>;</END>
		</SPAN>
	</RULES>

	<RULES SET="TAGS" DEFAULT="MARKUP">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<SPAN TYPE="LITERAL1">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">=</SEQ>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/shtml.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="commentStart" VALUE="&lt;!--" />
		<PROPERTY NAME="commentEnd" VALUE="--&gt;" />
	</PROPS>
	<RULES IGNORE_CASE="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>


		<!-- SSI -->
		<!-- SSI directives should ALWAYS end like this, with a space
			before the tag end, so let's make it colorize poorly otherwise -->
		<SPAN TYPE="KEYWORD3" DELEGATE="SSI">
			<BEGIN>&lt;!--#</BEGIN>
			<END> --&gt;</END>
		</SPAN>

		<!-- SGML comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>&lt;!--</BEGIN>
			<END>--&gt;</END>
		</SPAN>

		<!-- JavaScript -->
		<SPAN TYPE="MARKUP" DELEGATE="javascript::MAIN">
			<BEGIN>&lt;SCRIPT&gt;</BEGIN>
			<END>&lt;/SCRIPT&gt;</END>
		</SPAN>

		<SPAN TYPE="MARKUP" DELEGATE="javascript::MAIN">
			<BEGIN>&lt;SCRIPT language="JavaScript"&gt;</BEGIN>
			<END>&lt;/SCRIPT&gt;</END>
		</SPAN>

		<SPAN TYPE="MARKUP" DELEGATE="javascript::MAIN">
			<BEGIN>&lt;SCRIPT language="JavaScript1.1"&gt;</BEGIN>
			<END>&lt;/SCRIPT&gt;</END>
		</SPAN>

		<SPAN TYPE="MARKUP" DELEGATE="javascript::MAIN">
			<BEGIN>&lt;SCRIPT language="JavaScript1.2"&gt;</BEGIN>
			<END>&lt;/SCRIPT&gt;</END>
		</SPAN>

		<!-- stylesheet -->
		<SPAN TYPE="MARKUP" DELEGATE="css::MAIN">
			<BEGIN>&lt;STYLE&gt;</BEGIN>
			<END>&lt;/STYLE&gt;</END>
		</SPAN>

		<!-- DTD instructions -->
		<SPAN TYPE="KEYWORD2" DELEGATE="xml::DTD-TAGS">
			<BEGIN>&lt;!</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- markup tags -->
		<SPAN TYPE="MARKUP" DELEGATE="TAGS">
			<BEGIN>&lt;</BEGIN>
			<END>&gt;</END>
		</SPAN>

		<!-- SGML entities -->
		<SPAN TYPE="LITERAL2" NO_WORD_BREAK="TRUE">
			<BEGIN>&amp;</BEGIN>
			<END>;</END>
		</SPAN>
	</RULES>

	<RULES SET="TAGS" DEFAULT="MARKUP">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<SPAN TYPE="LITERAL1">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<SPAN TYPE="LITERAL1">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">=</SEQ>
	</RULES>

	<RULES SET="SSI" DEFAULT="KEYWORD3">
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<SPAN TYPE="LITERAL1" EXCLUDE_MATCH="TRUE" DELEGATE="SSI-EXPRESSION">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>

		<!-- MD: i don't think this is valid
		<SPAN TYPE="LITERAL1" EXCLUDE_MATCH="TRUE" DELEGATE="SSI-EXPRESSION">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>
		-->

		<SEQ TYPE="OPERATOR">=</SEQ>

		<KEYWORDS>
			<KEYWORD1>config</KEYWORD1>
			<KEYWORD1>echo</KEYWORD1>
			<KEYWORD1>exec</KEYWORD1>
			<KEYWORD1>flastmod</KEYWORD1>
			<KEYWORD1>fsize</KEYWORD1>
			<KEYWORD1>include</KEYWORD1>

			<KEYWORD2>cgi</KEYWORD2>
			<KEYWORD2>errmsg</KEYWORD2>
			<KEYWORD2>file</KEYWORD2>
			<KEYWORD2>sizefmt</KEYWORD2>
			<KEYWORD2>timefmt</KEYWORD2>
			<KEYWORD2>var</KEYWORD2>
			<KEYWORD2>cmd</KEYWORD2>
		</KEYWORDS>
	</RULES>

	<RULES SET="SSI-EXPRESSION" DEFAULT="LITERAL1" ESCAPE="\">

		<MARK_FOLLOWING TYPE="KEYWORD2">$</MARK_FOLLOWING>

		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&amp;&amp;</SEQ>
		<SEQ TYPE="OPERATOR">||</SEQ>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/props.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="#" />
	</PROPS>
	<RULES HIGHLIGHT_DIGITS="TRUE">
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<EOL_SPAN TYPE="COMMENT1" AT_LINE_START="TRUE">#</EOL_SPAN>
		<MARK_PREVIOUS TYPE="KEYWORD1"
			AT_LINE_START="TRUE" EXCLUDE_MATCH="TRUE">=</MARK_PREVIOUS>
		<MARK_PREVIOUS TYPE="KEYWORD1"
			AT_LINE_START="TRUE" EXCLUDE_MATCH="TRUE">:</MARK_PREVIOUS>
		<!-- MessageFormat { ... } stuff -->
		<SPAN TYPE="KEYWORD3" NO_LINE_BREAK="TRUE">
			<BEGIN>{</BEGIN>
			<END>}</END>
		</SPAN>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/cplusplus.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- Extension of c.xml to add C++ keywords. -->
<MODE>
    <PROPS>
        <PROPERTY NAME="commentStart" VALUE="/*" />
        <PROPERTY NAME="commentEnd" VALUE="*/" />
        <PROPERTY NAME="lineComment" VALUE="//" />
        <PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />


		<!-- Auto indent -->
		<PROPERTY NAME="indentOpenBrackets" VALUE="{" />
		<PROPERTY NAME="indentCloseBrackets" VALUE="}" />
		<PROPERTY NAME="unalignedOpenBrackets" VALUE="(" />
		<PROPERTY NAME="unalignedCloseBrackets" VALUE=")" />
		<PROPERTY NAME="indentNextLine"
			VALUE="\s*(((if|while)\s*\(|else\s*|else\s+if\s*\(|for\s*\(.*\))[^{;]*)" />
		<PROPERTY NAME="unindentThisLine"
			VALUE="^.*(default:\s*|case.*:.*)$" />
		<PROPERTY NAME="electricKeys" VALUE=":" />
    </PROPS>

    <RULES
        ESCAPE="\" IGNORE_CASE="FALSE"
        HIGHLIGHT_DIGITS="TRUE" DIGIT_RE="[0-9][0-9a-zA-Z]*">
        <EOL_SPAN TYPE="KEYWORD2" AT_WHITESPACE_END="TRUE" DELEGATE="CPP">#</EOL_SPAN>

        <IMPORT DELEGATE="c::LEX"/>
        <IMPORT DELEGATE="c::CORE"/>
        <IMPORT DELEGATE="CORE"/>
    </RULES>

    <!-- Core C++ language -->
    <RULES SET="CORE"
        ESCAPE="\" IGNORE_CASE="FALSE"
        HIGHLIGHT_DIGITS="TRUE" DIGIT_RE="[0-9][0-9a-zA-Z]*">
        <KEYWORDS>
            <KEYWORD3>class</KEYWORD3>
            <KEYWORD3>const_cast</KEYWORD3>
            <KEYWORD1>delete</KEYWORD1>
            <KEYWORD3>dynamic_cast</KEYWORD3>
            <KEYWORD1>explicit</KEYWORD1>
            <KEYWORD2>export</KEYWORD2>
            <KEYWORD1>friend</KEYWORD1>
            <KEYWORD3>mutable</KEYWORD3>
            <KEYWORD2>namespace</KEYWORD2>
            <KEYWORD1>new</KEYWORD1>
            <KEYWORD3>operator</KEYWORD3>
            <KEYWORD1>private</KEYWORD1>
            <KEYWORD1>protected</KEYWORD1>
            <KEYWORD1>public</KEYWORD1>
            <KEYWORD3>reinterpret_cast</KEYWORD3>
            <KEYWORD3>static_assert</KEYWORD3>
            <KEYWORD3>static_cast</KEYWORD3>
            <KEYWORD3>template</KEYWORD3>
            <LITERAL2>this</LITERAL2>
            <KEYWORD1>throw</KEYWORD1>
            <KEYWORD1>try</KEYWORD1>
            <KEYWORD3>typeid</KEYWORD3>
            <KEYWORD3>typename</KEYWORD3>
            <KEYWORD2>using</KEYWORD2>
            <KEYWORD1>virtual</KEYWORD1>
        </KEYWORDS>
    </RULES>

    <!-- Preprocessor specific rules -->
    <RULES SET="CPP"
        ESCAPE="\" IGNORE_CASE="FALSE"
        HIGHLIGHT_DIGITS="TRUE" DIGIT_RE="[0-9][0-9a-zA-Z]*">

        <EOL_SPAN_REGEXP HASH_CHAR="include" TYPE="MARKUP" DELEGATE="c::INCLUDE">include\b</EOL_SPAN_REGEXP>
        <EOL_SPAN_REGEXP HASH_CHAR="define" TYPE="MARKUP" DELEGATE="DEFINE">define\b</EOL_SPAN_REGEXP>
        <EOL_SPAN_REGEXP HASH_CHAR="endif" TYPE="MARKUP" DELEGATE="c::LEX">endif\b</EOL_SPAN_REGEXP>
        <EOL_SPAN_REGEXP HASH_CHAR="elif" TYPE="MARKUP" DELEGATE="c::CONDITION">elif\b</EOL_SPAN_REGEXP>
        <EOL_SPAN_REGEXP HASH_CHAR="if" TYPE="MARKUP" DELEGATE="c::CONDITION">if\b</EOL_SPAN_REGEXP>

        <IMPORT DELEGATE="c::LEX"/>

        <!-- Directives -->
        <KEYWORDS>
            <MARKUP>ifdef</MARKUP>
            <MARKUP>ifndef</MARKUP>
            <MARKUP>else</MARKUP>
            <MARKUP>error</MARKUP>
            <MARKUP>line</MARKUP>
            <MARKUP>pragma</MARKUP>
            <MARKUP>undef</MARKUP>
            <MARKUP>warning</MARKUP>
        </KEYWORDS>
    </RULES>

    <!-- After #define directive -->
    <!-- Almost same as the normal code,
        except two additional operators # and ##. -->
    <RULES SET="DEFINE"
        ESCAPE="\" IGNORE_CASE="FALSE"
        HIGHLIGHT_DIGITS="TRUE" DIGIT_RE="[0-9][0-9a-zA-Z]*">
        <SEQ TYPE="OPERATOR">#</SEQ>
        <IMPORT DELEGATE="c::LEX"/>
        <IMPORT DELEGATE="c::CORE"/>
        <IMPORT DELEGATE="CORE"/>
    </RULES>

</MODE>

=== vanzin/jEdit/modes/bibtex.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<!-- BibTeX mode, by Nils Krahnstoever <krahnsto@cse.psu.edu>
     based PV-WAVE mode by Ed Stewarton and tex mode by unknown author.
     updated by Stefan Kost <s.kost@webmacher.de>
-->

<MODE>
	<PROPS>
		<PROPERTY NAME="lineComment" VALUE="%" />
	</PROPS>
	<RULES>
		<!-- @... commands -->
		<MARK_FOLLOWING TYPE="KEYWORD2">@</MARK_FOLLOWING>

		<!-- comments -->
		<EOL_SPAN TYPE="COMMENT1">%</EOL_SPAN>

		<SPAN TYPE="MARKUP" DELEGATE="ENTRY">
			<BEGIN>{</BEGIN>
			<END>}</END>
		</SPAN>
	</RULES>
	<RULES SET="ENTRY" DEFAULT="MARKUP" IGNORE_CASE="TRUE">
		<SPAN TYPE="LITERAL1" DELEGATE="ITEM">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		
		<SPAN TYPE="LITERAL1" DELEGATE="ITEM">
			<BEGIN>{</BEGIN>
			<END>}</END>
		</SPAN>

		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">,</SEQ>

		<KEYWORDS>
			<KEYWORD1>address</KEYWORD1>
			<KEYWORD1>annote</KEYWORD1>
			<KEYWORD1>author</KEYWORD1>
			<KEYWORD1>title</KEYWORD1>
			<KEYWORD1>type</KEYWORD1>
			<KEYWORD1>abstract</KEYWORD1>
			<KEYWORD1>volume</KEYWORD1>
			<KEYWORD1>pages</KEYWORD1>
			<KEYWORD1>number</KEYWORD1>
			<KEYWORD1>note</KEYWORD1>
			<KEYWORD1>key</KEYWORD1>
			<KEYWORD1>organization</KEYWORD1>
			<KEYWORD1>school</KEYWORD1>
			<KEYWORD1>series</KEYWORD1>
			<KEYWORD1>chapter</KEYWORD1>
			<KEYWORD1>month</KEYWORD1>
			<KEYWORD1>department</KEYWORD1>
			<KEYWORD1>keywords</KEYWORD1>
			<KEYWORD1>howpublished</KEYWORD1>
			<KEYWORD1>institution</KEYWORD1>
			<KEYWORD1>journal</KEYWORD1>
			<KEYWORD1>publisher</KEYWORD1>
			<KEYWORD1>editon</KEYWORD1>
			<KEYWORD1>editor</KEYWORD1>
			<KEYWORD1>year</KEYWORD1>
			<KEYWORD1>booktitle</KEYWORD1>
		</KEYWORDS>
	</RULES>
	<RULES SET="ITEM" DEFAULT="LITERAL1">
		<SPAN TYPE="LITERAL1">
			<BEGIN>{</BEGIN>
			<END>}</END>
		</SPAN>
	</RULES>
</MODE>

=== vanzin/jEdit/modes/beanshell.xml
<?xml version="1.0"?>

<!DOCTYPE MODE SYSTEM "xmode.dtd">

<MODE>
	<PROPS>
		<!-- the ; hack is there so that stuff like if(bob) fred();
		     does not indent the next line -->
		<PROPERTY NAME="indentPrevLine" VALUE="\s*(((if|while)\s*\(|else|case|default)[^;]*|for\s*\(.*)" />
		<!-- set this to 'true' if you want to use GNU coding style -->
		<PROPERTY NAME="doubleBracketIndent" VALUE="false" />
		<PROPERTY NAME="indentOpenBrackets" VALUE="{" />
		<PROPERTY NAME="indentCloseBrackets" VALUE="}" />
		<PROPERTY NAME="commentStart" VALUE="/*" />
		<PROPERTY NAME="commentEnd" VALUE="*/" />
		<PROPERTY NAME="lineComment" VALUE="//" />
		<PROPERTY NAME="noWordSep" VALUE="_" />
		<PROPERTY NAME="wordBreakChars" VALUE=",+-=&lt;&gt;/?^&amp;*" />
	</PROPS>
	<RULES ESCAPE="\" IGNORE_CASE="FALSE" HIGHLIGHT_DIGITS="TRUE">
		<!-- whitespace: (space and tab) -->
		<WHITESPACE> </WHITESPACE>
		<WHITESPACE>	</WHITESPACE>

		<!-- C style comment -->
		<SPAN TYPE="COMMENT1">
			<BEGIN>/*</BEGIN>
			<END>*/</END>
		</SPAN>

		<!-- C++ style comment -->
		<EOL_SPAN TYPE="COMMENT1">//</EOL_SPAN>

		<!-- BeanShell comment -->
		<EOL_SPAN TYPE="COMMENT1">#!</EOL_SPAN>

		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>"</BEGIN>
			<END>"</END>
		</SPAN>
		<SPAN TYPE="LITERAL1" NO_LINE_BREAK="TRUE">
			<BEGIN>'</BEGIN>
			<END>'</END>
		</SPAN>

		<SEQ TYPE="NULL">)</SEQ>
		<SEQ TYPE="OPERATOR">=</SEQ>
		<SEQ TYPE="OPERATOR">!</SEQ>
		<SEQ TYPE="OPERATOR">&gt;=</SEQ>
		<SEQ TYPE="OPERATOR">&lt;=</SEQ>
		<SEQ TYPE="OPERATOR">+</SEQ>
		<SEQ TYPE="OPERATOR">-</SEQ>
		<SEQ TYPE="OPERATOR">/</SEQ>

		<SEQ TYPE="OPERATOR">*</SEQ>
		<SEQ TYPE="OPERATOR">&gt;</SEQ>
		<SEQ TYPE="OPERATOR">&lt;</SEQ>
		<SEQ TYPE="OPERATOR">%</SEQ>
		<SEQ TYPE="OPERATOR">&amp;</SEQ>
		<SEQ TYPE="OPERATOR">|</SEQ>
		<SEQ TYPE="OPERATOR">^</SEQ>
		<SEQ TYPE="OPERATOR">~</SEQ>
		<SEQ TYPE="OPERATOR">}</SEQ>
		<SEQ TYPE="OPERATOR">{</SEQ>
		<SEQ TYPE="NULL">.</SEQ>
		<SEQ TYPE="NULL">,</SEQ>
		<SEQ TYPE="NULL">;</SEQ>
		<SEQ TYPE="NULL">]</SEQ>
		<SEQ TYPE="NULL">[</SEQ>
		<SEQ TYPE="NULL">?</SEQ>
		<MARK_PREVIOUS TYPE="LABEL" EXCLUDE_MATCH="TRUE"
			AT_LINE_START="TRUE">:</MARK_PREVIOUS>
		<SEQ TYPE="NULL">:</SEQ>

		<!-- Function calls -->
		<MARK_PREVIOUS TYPE="FUNCTION" EXCLUDE_MATCH="TRUE">(</MARK_PREVIOUS>

		<KEYWORDS IGNORE_CASE="FALSE">
			<KEYWORD2>import</KEYWORD2>
			<KEYWORD3>byte</KEYWORD3>
			<KEYWORD3>char</KEYWORD3>
			<KEYWORD3>short</KEYWORD3>
			<KEYWORD3>int</KEYWORD3>
			<KEYWORD3>long</KEYWORD3>
			<KEYWORD3>float</KEYWORD3>
			<KEYWORD3>double</KEYWORD3>
			<KEYWORD3>boolean</KEYWORD3>
			<KEYWORD3>void</KEYWORD3>
			<KEYWORD1>break</KEYWORD1>
			<KEYWORD1>case</KEYWORD1>
			<KEYWORD1>continue</KEYWORD1>
			<KEYWORD1>default</KEYWORD1>
			<KEYWORD1>do</KEYWORD1>
			<KEYWORD1>else</KEYWORD1>
			<KEYWORD1>for</KEYWORD1>
			<KEYWORD1>if</KEYWORD1>
			<KEYWORD1>instanceof</KEYWORD1>
			<KEYWORD1>new</KEYWORD1>
			<KEYWORD1>return</KEYWORD1>
			<KEYWORD1>switch</KEYWORD1>
			<KEYWORD1>while</KEYWORD1>
			<KEYWORD1>throw</KEYWORD1>
			<KEYWORD1>try</KEYWORD1>
			<KEYWORD1>catch</KEYWORD1>
			<KEYWORD1>finally</KEYWORD1>
			<LITERAL2>this</LITERAL2>
			<LITERAL2>null</LITERAL2>
			<LITERAL2>true</LITERAL2>
			<LITERAL2>false</LITERAL2>
		</KEYWORDS>
	</RULES>
</MODE>
